-- Schema + Seed data for ShopThuCungDB
-- This script creates tables and inserts sample categories/products.
-- NOTE: Identity users are NOT inserted here because PasswordHash must be generated by ASP.NET Identity.

IF DB_ID('ShopThuCungDB') IS NULL
BEGIN
    CREATE DATABASE ShopThuCungDB;
END
GO

USE ShopThuCungDB;
GO

-- =========================
-- ASP.NET Identity tables
-- =========================
IF OBJECT_ID(N'[dbo].[AspNetRoles]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AspNetRoles](
        [Id] nvarchar(450) NOT NULL,
        [Name] nvarchar(256) NULL,
        [NormalizedName] nvarchar(256) NULL,
        [ConcurrencyStamp] nvarchar(max) NULL,
        CONSTRAINT [PK_AspNetRoles] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF OBJECT_ID(N'[dbo].[AspNetUsers]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AspNetUsers](
        [Id] nvarchar(450) NOT NULL,
        [Address] nvarchar(255) NULL,
        [FullName] nvarchar(max) NULL,
        [UserName] nvarchar(256) NULL,
        [NormalizedUserName] nvarchar(256) NULL,
        [Email] nvarchar(256) NOT NULL,
        [NormalizedEmail] nvarchar(256) NULL,
        [EmailConfirmed] bit NOT NULL,
        [PasswordHash] nvarchar(max) NOT NULL,
        [SecurityStamp] nvarchar(max) NULL,
        [ConcurrencyStamp] nvarchar(max) NULL,
        [PhoneNumber] nvarchar(max) NULL,
        [PhoneNumberConfirmed] bit NOT NULL,
        [TwoFactorEnabled] bit NOT NULL,
        [LockoutEnd] datetimeoffset NULL,
        [LockoutEnabled] bit NOT NULL,
        [AccessFailedCount] int NOT NULL,
        CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF OBJECT_ID(N'[dbo].[AspNetRoleClaims]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AspNetRoleClaims](
        [Id] int IDENTITY(1,1) NOT NULL,
        [RoleId] nvarchar(450) NOT NULL,
        [ClaimType] nvarchar(max) NULL,
        [ClaimValue] nvarchar(max) NULL,
        CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF OBJECT_ID(N'[dbo].[AspNetUserClaims]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AspNetUserClaims](
        [Id] int IDENTITY(1,1) NOT NULL,
        [UserId] nvarchar(450) NOT NULL,
        [ClaimType] nvarchar(max) NULL,
        [ClaimValue] nvarchar(max) NULL,
        CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF OBJECT_ID(N'[dbo].[AspNetUserLogins]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AspNetUserLogins](
        [LoginProvider] nvarchar(450) NOT NULL,
        [ProviderKey] nvarchar(450) NOT NULL,
        [ProviderDisplayName] nvarchar(max) NULL,
        [UserId] nvarchar(450) NOT NULL,
        CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY CLUSTERED ([LoginProvider] ASC, [ProviderKey] ASC)
    );
END
GO

IF OBJECT_ID(N'[dbo].[AspNetUserRoles]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AspNetUserRoles](
        [UserId] nvarchar(450) NOT NULL,
        [RoleId] nvarchar(450) NOT NULL,
        CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC)
    );
END
GO

IF OBJECT_ID(N'[dbo].[AspNetUserTokens]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[AspNetUserTokens](
        [UserId] nvarchar(450) NOT NULL,
        [LoginProvider] nvarchar(450) NOT NULL,
        [Name] nvarchar(450) NOT NULL,
        [Value] nvarchar(max) NULL,
        CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY CLUSTERED ([UserId] ASC, [LoginProvider] ASC, [Name] ASC)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'RoleNameIndex' AND object_id = OBJECT_ID('AspNetRoles'))
    CREATE UNIQUE INDEX [RoleNameIndex] ON [dbo].[AspNetRoles] ([NormalizedName]) WHERE [NormalizedName] IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'EmailIndex' AND object_id = OBJECT_ID('AspNetUsers'))
    CREATE INDEX [EmailIndex] ON [dbo].[AspNetUsers] ([NormalizedEmail]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UserNameIndex' AND object_id = OBJECT_ID('AspNetUsers'))
    CREATE UNIQUE INDEX [UserNameIndex] ON [dbo].[AspNetUsers] ([NormalizedUserName]) WHERE [NormalizedUserName] IS NOT NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AspNetRoleClaims_AspNetRoles_RoleId')
    ALTER TABLE [dbo].[AspNetRoleClaims] ADD CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId]
    FOREIGN KEY ([RoleId]) REFERENCES [dbo].[AspNetRoles] ([Id]) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AspNetUserClaims_AspNetUsers_UserId')
    ALTER TABLE [dbo].[AspNetUserClaims] ADD CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId]
    FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AspNetUserLogins_AspNetUsers_UserId')
    ALTER TABLE [dbo].[AspNetUserLogins] ADD CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId]
    FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AspNetUserRoles_AspNetRoles_RoleId')
    ALTER TABLE [dbo].[AspNetUserRoles] ADD CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId]
    FOREIGN KEY ([RoleId]) REFERENCES [dbo].[AspNetRoles] ([Id]) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AspNetUserRoles_AspNetUsers_UserId')
    ALTER TABLE [dbo].[AspNetUserRoles] ADD CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId]
    FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_AspNetUserTokens_AspNetUsers_UserId')
    ALTER TABLE [dbo].[AspNetUserTokens] ADD CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId]
    FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;
GO

-- =========================
-- Shop tables
-- =========================
IF OBJECT_ID(N'[dbo].[Categories]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[Categories](
        [Id] int IDENTITY(1,1) NOT NULL,
        [Name] nvarchar(100) NOT NULL,
        [Description] nvarchar(500) NULL,
        [ImageUrl] nvarchar(255) NULL,
        [IsActive] bit NOT NULL,
        CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF OBJECT_ID(N'[dbo].[Products]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[Products](
        [Id] int IDENTITY(1,1) NOT NULL,
        [Name] nvarchar(200) NOT NULL,
        [Description] nvarchar(2000) NULL,
        [Price] decimal(18,2) NOT NULL,
        [OldPrice] decimal(18,2) NULL,
        [ImageUrl] nvarchar(255) NULL,
        [CategoryId] int NOT NULL,
        [Stock] int NOT NULL,
        [Rating] decimal(3,2) NOT NULL,
        [ReviewCount] int NOT NULL,
        [IsActive] bit NOT NULL,
        [CreatedDate] datetime2 NOT NULL,
        CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Products_Categories_CategoryId')
    ALTER TABLE [dbo].[Products] ADD CONSTRAINT [FK_Products_Categories_CategoryId]
    FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories] ([Id]) ON DELETE NO ACTION;
GO

IF OBJECT_ID(N'[dbo].[Orders]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[Orders](
        [Id] int IDENTITY(1,1) NOT NULL,
        [UserId] nvarchar(450) NOT NULL,
        [OrderDate] datetime2 NOT NULL,
        [TotalAmount] decimal(18,2) NOT NULL,
        [Status] nvarchar(50) NOT NULL,
        [ShippingAddress] nvarchar(500) NULL,
        [ShippingName] nvarchar(100) NULL,
        [ShippingPhone] nvarchar(20) NULL,
        [Notes] nvarchar(500) NULL,
        CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Orders_AspNetUsers_UserId')
    ALTER TABLE [dbo].[Orders] ADD CONSTRAINT [FK_Orders_AspNetUsers_UserId]
    FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE NO ACTION;
GO

IF OBJECT_ID(N'[dbo].[OrderDetails]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[OrderDetails](
        [Id] int IDENTITY(1,1) NOT NULL,
        [OrderId] int NOT NULL,
        [ProductId] int NOT NULL,
        [Quantity] int NOT NULL,
        [Price] decimal(18,2) NOT NULL,
        CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_OrderDetails_Orders_OrderId')
    ALTER TABLE [dbo].[OrderDetails] ADD CONSTRAINT [FK_OrderDetails_Orders_OrderId]
    FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Orders] ([Id]) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_OrderDetails_Products_ProductId')
    ALTER TABLE [dbo].[OrderDetails] ADD CONSTRAINT [FK_OrderDetails_Products_ProductId]
    FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([Id]) ON DELETE NO ACTION;
GO

IF OBJECT_ID(N'[dbo].[Carts]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[Carts](
        [Id] int IDENTITY(1,1) NOT NULL,
        [UserId] nvarchar(450) NOT NULL,
        [ProductId] int NOT NULL,
        [Quantity] int NOT NULL,
        [AddedDate] datetime2 NOT NULL,
        CONSTRAINT [PK_Carts] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Carts_AspNetUsers_UserId')
    ALTER TABLE [dbo].[Carts] ADD CONSTRAINT [FK_Carts_AspNetUsers_UserId]
    FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Carts_Products_ProductId')
    ALTER TABLE [dbo].[Carts] ADD CONSTRAINT [FK_Carts_Products_ProductId]
    FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([Id]) ON DELETE CASCADE;
GO

IF OBJECT_ID(N'[dbo].[Reviews]', N'U') IS NULL
BEGIN
    CREATE TABLE [dbo].[Reviews](
        [Id] int IDENTITY(1,1) NOT NULL,
        [ProductId] int NOT NULL,
        [UserId] nvarchar(450) NOT NULL,
        [Rating] int NOT NULL,
        [Comment] nvarchar(1000) NULL,
        [CreatedDate] datetime2 NOT NULL,
        CONSTRAINT [PK_Reviews] PRIMARY KEY CLUSTERED ([Id] ASC)
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Reviews_Products_ProductId')
    ALTER TABLE [dbo].[Reviews] ADD CONSTRAINT [FK_Reviews_Products_ProductId]
    FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([Id]) ON DELETE CASCADE;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Reviews_AspNetUsers_UserId')
    ALTER TABLE [dbo].[Reviews] ADD CONSTRAINT [FK_Reviews_AspNetUsers_UserId]
    FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE NO ACTION;
GO

-- Helpful indexes
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_Products_CategoryId' AND object_id = OBJECT_ID('Products'))
    CREATE INDEX [IX_Products_CategoryId] ON [dbo].[Products] ([CategoryId]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_Orders_UserId' AND object_id = OBJECT_ID('Orders'))
    CREATE INDEX [IX_Orders_UserId] ON [dbo].[Orders] ([UserId]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_OrderDetails_OrderId' AND object_id = OBJECT_ID('OrderDetails'))
    CREATE INDEX [IX_OrderDetails_OrderId] ON [dbo].[OrderDetails] ([OrderId]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_OrderDetails_ProductId' AND object_id = OBJECT_ID('OrderDetails'))
    CREATE INDEX [IX_OrderDetails_ProductId] ON [dbo].[OrderDetails] ([ProductId]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_Carts_ProductId' AND object_id = OBJECT_ID('Carts'))
    CREATE INDEX [IX_Carts_ProductId] ON [dbo].[Carts] ([ProductId]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_Carts_UserId_ProductId' AND object_id = OBJECT_ID('Carts'))
    CREATE UNIQUE INDEX [IX_Carts_UserId_ProductId] ON [dbo].[Carts] ([UserId], [ProductId]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_Reviews_UserId_ProductId' AND object_id = OBJECT_ID('Reviews'))
    CREATE UNIQUE INDEX [IX_Reviews_UserId_ProductId] ON [dbo].[Reviews] ([UserId], [ProductId]);
GO

-- =========================
-- Seed data (Categories + Products)
-- =========================
DELETE FROM Reviews;
DELETE FROM Carts;
DELETE FROM OrderDetails;
DELETE FROM Orders;
DELETE FROM Products;
DELETE FROM Categories;
GO

DBCC CHECKIDENT ('Reviews', RESEED, 0);
DBCC CHECKIDENT ('Products', RESEED, 0);
DBCC CHECKIDENT ('Categories', RESEED, 0);
GO

SET IDENTITY_INSERT Categories ON;
INSERT INTO Categories (Id, Name, Description, IsActive) VALUES
(1, N'Thức Ăn', N'Thức ăn dinh dưỡng cho thú cưng', 1),
(2, N'Đồ Chơi', N'Đồ chơi vui nhộn cho thú cưng', 1),
(3, N'Phụ Kiện', N'Phụ kiện và đồ dùng cho thú cưng', 1),
(4, N'Chăm Sóc', N'Sản phẩm chăm sóc sức khỏe thú cưng', 1);
SET IDENTITY_INSERT Categories OFF;
GO

SET IDENTITY_INSERT Products ON;
-- Group 1: Dogs (25)
INSERT INTO Products (Id, Name, Description, Price, OldPrice, ImageUrl, CategoryId, Stock, Rating, ReviewCount, IsActive, CreatedDate) VALUES
(1, N'Chó Alaska Nâu Đỏ', N'<p>Alaska size tiêu chuẩn, lông dày.</p>', 5500000, 6000000, N'/products/dog/sp1.jpg', 1, 5, 5, 12, 1, GETDATE()),
(2, N'Chó Alaska Giant Mặt Gấu', N'<p>Dòng Giant khung xương to.</p>', 7200000, 8000000, N'/products/dog/sp2.jpg', 1, 3, 4.5, 8, 1, GETDATE()),
(3, N'Corgi Pembroke Nhập Thái', N'<p>Corgi mông trái tim, nhập Thái.</p>', 4800000, 0, N'/products/dog/sp3.jpg', 1, 10, 5, 25, 1, GETDATE()),
(4, N'Corgi Teacup Mini', N'<p>Size nhỏ nhắn, chân ngắn.</p>', 3900000, 4500000, N'/products/dog/sp4.jpg', 1, 6, 4, 5, 1, GETDATE()),
(5, N'Corgi Tricolor (3 Màu)', N'<p>Màu lông 3 màu hiếm gặp.</p>', 5200000, 5500000, N'/products/dog/sp5.jpg', 1, 4, 4.5, 10, 1, GETDATE()),
(6, N'Corgi Baby Vàng Trắng', N'<p>Bé Corgi 2 tháng tuổi.</p>', 4800000, 5200000, N'/products/dog/sp6.jpg', 1, 5, 5, 8, 1, GETDATE()),
(7, N'Corgi Màu Đen Chân Trắng', N'<p>Màu lông tối độc đáo.</p>', 5000000, 0, N'/products/dog/sp7.jpg', 1, 3, 4.5, 4, 1, GETDATE()),
(8, N'Corgi Tricolor Mặt Cân', N'<p>Vạch mặt cân đối, tai dựng.</p>', 5500000, 6000000, N'/products/dog/sp8.jpg', 1, 4, 5, 12, 1, GETDATE()),
(9, N'Pomeranian Mini Kem', N'<p>Phốc sóc size Mini, lông xù.</p>', 6200000, 7000000, N'/products/dog/sp9.jpg', 1, 6, 5, 20, 1, GETDATE()),
(10, N'Phốc Sóc Teacup Trắng', N'<p>Dòng Teacup nhỏ xíu, trắng tinh.</p>', 7500000, 8000000, N'/products/dog/sp10.jpg', 1, 2, 5, 35, 1, GETDATE()),
(11, N'Phốc Sóc Vàng Cam', N'<p>Màu vàng cam truyền thống.</p>', 5800000, 0, N'/products/dog/sp11.jpg', 1, 5, 4.5, 10, 1, GETDATE()),
(12, N'Phốc Sóc Đen Tuyền', N'<p>Màu đen tuyền hiếm gặp.</p>', 6500000, 0, N'/products/dog/sp12.jpg', 1, 3, 4, 5, 1, GETDATE()),
(13, N'Phốc Sóc Panda', N'<p>Màu lông bò sữa cực độc.</p>', 8500000, 9000000, N'/products/dog/sp13.jpg', 1, 1, 5, 40, 1, GETDATE()),
(14, N'Poodle Tiny Trắng', N'<p>Lông xoăn trắng muốt.</p>', 4200000, 4500000, N'/products/dog/sp14.jpg', 1, 10, 4.5, 15, 1, GETDATE()),
(15, N'Poodle Tiny Nâu Socola', N'<p>Màu nâu Chocolate sạch sẽ.</p>', 4500000, 4800000, N'/products/dog/sp15.jpg', 1, 8, 5, 22, 1, GETDATE()),
(16, N'Poodle Tiny Vàng Mơ', N'<p>Màu vàng mơ ngọt ngào.</p>', 4500000, 5000000, N'/products/dog/sp16.jpg', 1, 8, 5, 12, 1, GETDATE()),
(17, N'Poodle Tiny Màu Kem', N'<p>Màu kem sáng, lông dày.</p>', 4600000, 0, N'/products/dog/sp17.jpg', 1, 6, 4.5, 9, 1, GETDATE()),
(18, N'Poodle Tiny Nâu Đỏ', N'<p>Màu nâu đỏ chuẩn.</p>', 4800000, 5200000, N'/products/dog/sp18.jpg', 1, 10, 5, 20, 1, GETDATE()),
(19, N'Poodle Teacup Vàng Kem', N'<p>Size Teacup siêu nhỏ.</p>', 4700000, 0, N'/products/dog/sp19.jpg', 1, 4, 4, 5, 1, GETDATE()),
(20, N'Poodle Phantom', N'<p>Màu Phantom cực cá tính.</p>', 6500000, 7500000, N'/products/dog/sp20.jpg', 1, 2, 5, 30, 1, GETDATE()),
(21, N'Chow Chow Mini Cream', N'<p>Chó gấu Chow Chow lông xù.</p>', 7500000, 8000000, N'/products/dog/sp21.jpg', 1, 3, 5, 15, 1, GETDATE()),
(22, N'Chow Chow Lưỡi Xanh', N'<p>Lưỡi xanh tím huyền thoại.</p>', 8000000, 0, N'/products/dog/sp22.jpg', 1, 2, 4.5, 8, 1, GETDATE()),
(23, N'Chow Chow Nâu Vàng', N'<p>Mặt gấu nị nẫm.</p>', 8500000, 9200000, N'/products/dog/sp23.jpg', 1, 1, 5, 10, 1, GETDATE()),
(24, N'Chow Chow Trắng Tuyết', N'<p>Màu trắng tuyết hiếm có.</p>', 9000000, 10000000, N'/products/dog/sp24.jpg', 1, 1, 5, 25, 1, GETDATE()),
(25, N'Bull Pháp Bò Sữa', N'<p>Bull Pháp màu bò sữa.</p>', 7000000, 7800000, N'/products/dog/sp25.jpg', 1, 5, 4.5, 18, 1, GETDATE());

-- Group 2: Cats (25)
INSERT INTO Products (Id, Name, Description, Price, OldPrice, ImageUrl, CategoryId, Stock, Rating, ReviewCount, IsActive, CreatedDate) VALUES
(26, N'Mèo Anh Tabby', N'<p>Màu vằn cổ điển.</p>', 3500000, 3800000, N'/products/cat/sp01.jpg', 2, 8, 4.5, 6, 1, GETDATE()),
(27, N'Scottish Fold Silver', N'<p>Tai cụp màu Silver.</p>', 4500000, 5000000, N'/products/cat/sp02.jpg', 2, 5, 5, 15, 1, GETDATE()),
(28, N'Tai Cụp Xám Xanh', N'<p>Màu Blue lông mịn.</p>', 4200000, 0, N'/products/cat/sp03.jpg', 2, 4, 4, 3, 1, GETDATE()),
(29, N'Mèo ALN Blue Baby', N'<p>Mèo con 2 tháng tuổi.</p>', 3200000, 3500000, N'/products/cat/sp04.jpg', 2, 10, 5, 9, 1, GETDATE()),
(30, N'Mèo ALN Lilac', N'<p>Màu Lilac mắt hổ phách.</p>', 3800000, 4000000, N'/products/cat/sp05.jpg', 2, 2, 4.5, 11, 1, GETDATE()),
(31, N'Maine Coon Red Tabby', N'<p>Mèo khổng lồ Mỹ.</p>', 8500000, 9500000, N'/products/cat/sp06.jpg', 2, 2, 5, 10, 1, GETDATE()),
(32, N'Scottish Fold Blue', N'<p>Tai cụp xám xanh.</p>', 4200000, 0, N'/products/cat/sp07.jpg', 2, 5, 4, 6, 1, GETDATE()),
(33, N'ALN Trắng Tinh', N'<p>Màu trắng mắt xanh.</p>', 5500000, 6000000, N'/products/cat/sp08.jpg', 2, 3, 5, 15, 1, GETDATE()),
(34, N'ALN Black', N'<p>Đen tuyền huyền bí.</p>', 4800000, 0, N'/products/cat/sp09.jpg', 2, 4, 4.5, 8, 1, GETDATE()),
(35, N'Scottish Fold Cream', N'<p>Màu kem sữa.</p>', 4500000, 5000000, N'/products/cat/sp10.jpg', 2, 6, 4.5, 12, 1, GETDATE()),
(36, N'Tai Cụp Trắng', N'<p>Trắng tinh khôi.</p>', 5200000, 0, N'/products/cat/sp11.jpg', 2, 3, 5, 20, 1, GETDATE()),
(37, N'Scottish Fold Bicolor', N'<p>Vàng trắng cân đối.</p>', 4600000, 0, N'/products/cat/sp12.jpg', 2, 5, 4, 5, 1, GETDATE()),
(38, N'Munchkin Tai Cụp', N'<p>Chân ngắn tai cụp.</p>', 9500000, 12000000, N'/products/cat/sp13.jpg', 2, 1, 5, 30, 1, GETDATE()),
(39, N'Scottish Bicolor Xám', N'<p>Xám trắng Tuxedo.</p>', 4800000, 5200000, N'/products/cat/sp14.jpg', 2, 4, 4.5, 9, 1, GETDATE()),
(40, N'Scottish Silver Tabby', N'<p>Màu Silver ánh bạc.</p>', 5000000, 5500000, N'/products/cat/sp15.jpg', 2, 3, 5, 18, 1, GETDATE()),
(41, N'Scottish Straight', N'<p>Tai thẳng màu Silver.</p>', 4500000, 5000000, N'/products/cat/sp16.jpg', 2, 5, 5, 10, 1, GETDATE()),
(42, N'Scottish Fold Bicolor', N'<p>Tai cụp sát.</p>', 5500000, 6000000, N'/products/cat/sp17.jpg', 2, 3, 4.5, 8, 1, GETDATE()),
(43, N'ALN Bicolor Mặt Nạ', N'<p>Khoang mặt cân đối.</p>', 4800000, 0, N'/products/cat/sp18.jpg', 2, 6, 5, 15, 1, GETDATE()),
(44, N'Munchkin Trắng', N'<p>Chân ngắn mắt cam.</p>', 8500000, 9500000, N'/products/cat/sp19.jpg', 2, 2, 5, 25, 1, GETDATE()),
(45, N'Munchkin Silver', N'<p>Chân ngắn Silver.</p>', 12000000, 13500000, N'/products/cat/sp20.jpg', 2, 1, 5, 40, 1, GETDATE()),
(46, N'Scottish Fold Tabby', N'<p>Họa tiết vằn dưa.</p>', 4200000, 4800000, N'/products/cat/sp21.jpg', 2, 4, 4.5, 12, 1, GETDATE()),
(47, N'Scottish Fold Blue', N'<p>Form người tròn vo.</p>', 5800000, 6500000, N'/products/cat/sp22.jpg', 2, 3, 5, 30, 1, GETDATE()),
(48, N'Ragdoll Bicolor', N'<p>Mắt xanh biếc.</p>', 9000000, 0, N'/products/cat/sp23.jpg', 2, 2, 5, 18, 1, GETDATE()),
(49, N'Ba Tư Chocolate', N'<p>Lông dài xù bông.</p>', 6500000, 7200000, N'/products/cat/sp24.jpg', 2, 2, 4, 5, 1, GETDATE()),
(50, N'ALN Trưởng Thành', N'<p>Mèo form to khỏe.</p>', 4000000, 4500000, N'/products/cat/sp25.jpg', 2, 5, 4.5, 20, 1, GETDATE());

-- Group 3: Accessories (25)
INSERT INTO Products (Id, Name, Description, Price, OldPrice, ImageUrl, CategoryId, Stock, Rating, ReviewCount, IsActive, CreatedDate) VALUES
(51, N'Bóng Dây Thừng', N'<p>Đồ chơi bóng gặm.</p>', 45000, 55000, N'/products/phukien/sp1.jpg', 3, 50, 4, 20, 1, GETDATE()),
(52, N'Dây Thừng Sạch Răng', N'<p>Giúp sạch răng cún.</p>', 30000, 0, N'/products/phukien/sp2.jpg', 3, 100, 4, 15, 1, GETDATE()),
(53, N'Bàn Chải Đánh Răng', N'<p>Combo bàn chải kem.</p>', 85000, 100000, N'/products/phukien/sp3.jpg', 3, 30, 5, 10, 1, GETDATE()),
(54, N'Xẻng Xúc Cát', N'<p>Nhựa cứng bền.</p>', 15000, 20000, N'/products/phukien/sp8.jpg', 3, 100, 4, 45, 1, GETDATE()),
(55, N'Tấm Lót Vệ Sinh', N'<p>Siêu thấm hút.</p>', 95000, 110000, N'/products/phukien/sp9.jpg', 3, 40, 4.5, 30, 1, GETDATE()),
(56, N'Phấn Tắm Khô', N'<p>Khử mùi không cần nước.</p>', 65000, 0, N'/products/phukien/sp11.jpg', 3, 20, 4, 10, 1, GETDATE()),
(57, N'Sữa Tắm SOS', N'<p>Giữ màu lông.</p>', 90000, 100000, N'/products/phukien/sp12.jpg', 3, 35, 5, 50, 1, GETDATE()),
(58, N'Bát Ăn Đôi', N'<p>Bát nhựa giá rẻ.</p>', 25000, 30000, N'/products/phukien/sp15.jpg', 3, 80, 4, 18, 1, GETDATE()),
(59, N'Lược Chải Lông Spa', N'<p>Massage thư giãn.</p>', 120000, 150000, N'/products/phukien/sp4.jpg', 3, 20, 4.5, 5, 1, GETDATE()),
(60, N'Nệm Tròn Lông Cừu', N'<p>Siêu êm ái.</p>', 250000, 300000, N'/products/phukien/sp5.jpg', 3, 15, 5, 30, 1, GETDATE()),
(61, N'Bỉm Tã Hipidog', N'<p>Bịch bỉm cho chó.</p>', 120000, 150000, N'/products/phukien/sp10.jpg', 3, 25, 5, 15, 1, GETDATE()),
(62, N'Bỉm Quần Vệ Sinh', N'<p>Cho chó cái.</p>', 110000, 135000, N'/products/phukien/sp13.jpg', 3, 30, 4.5, 8, 1, GETDATE()),
(63, N'Hạt Royal Canin Poodle', N'<p>Túi 500g.</p>', 185000, 200000, N'/products/phukien/sp14.jpg', 3, 60, 5, 100, 1, GETDATE()),
(64, N'Bộ Dây Dắt Jean', N'<p>Phong cách bò.</p>', 120000, 150000, N'/products/phukien/sp18.jpg', 3, 20, 4.5, 15, 1, GETDATE()),
(65, N'Dây Dắt Họa Tiết', N'<p>Nhiều hình cute.</p>', 150000, 180000, N'/products/phukien/sp19.jpg', 3, 30, 4, 12, 1, GETDATE()),
(66, N'Dây Dắt Caro', N'<p>Thanh lịch.</p>', 130000, 0, N'/products/phukien/sp20.jpg', 3, 25, 4.5, 8, 1, GETDATE()),
(67, N'Bát Đôi Lúa Mạch', N'<p>Nhựa an toàn.</p>', 150000, 0, N'/products/phukien/sp6.jpg', 3, 50, 4.5, 12, 1, GETDATE()),
(68, N'Bọt Rửa Chân Cao Cấp', N'<p>Chai lớn 500ml.</p>', 350000, 400000, N'/products/phukien/sp7.jpg', 3, 30, 5, 20, 1, GETDATE()),
(69, N'Bát Ăn Đôi Hình Xương', N'<p>Bát sứ cao cấp.</p>', 320000, 350000, N'/products/phukien/sp16.jpg', 3, 50, 4.5, 10, 1, GETDATE()),
(70, N'Bát Inox Gắn Chuồng', N'<p>Inox 304 dày dặn.</p>', 300000, 0, N'/products/phukien/sp17.jpg', 3, 40, 5, 25, 1, GETDATE()),
(71, N'Bóng Cao Su 7 Màu (Set)', N'<p>Set 10 quả bóng.</p>', 400000, 0, N'/products/phukien/sp21.jpg', 3, 60, 4, 30, 1, GETDATE()),
(72, N'Dây Thừng 3 Nút (Combo)', N'<p>Combo 5 dây thừng lớn.</p>', 350000, 0, N'/products/phukien/sp22.jpg', 3, 50, 5, 20, 1, GETDATE()),
(73, N'Dây Thừng Hình Xương (Set)', N'<p>Set 5 món đồ chơi.</p>', 450000, 550000, N'/products/phukien/sp23.jpg', 3, 40, 4.5, 18, 1, GETDATE()),
(74, N'Bóng Dây Thừng Pastel (L)', N'<p>Size L cho chó lớn.</p>', 300000, 0, N'/products/phukien/sp24.jpg', 3, 70, 4, 40, 1, GETDATE()),
(75, N'Dây Dắt Cầu Vồng (Bộ)', N'<p>Full bộ yếm và dây.</p>', 450000, 500000, N'/products/phukien/sp25.jpg', 3, 35, 5, 22, 1, GETDATE());
SET IDENTITY_INSERT Products OFF;
GO

UPDATE Products SET Rating = ROUND(Rating, 0);
GO
